# intall refer to: https://haproxy.debian.net/

- name: Prepare for install
  shell: |
    apt-get install -y --no-install-recommends software-properties-common
    add-apt-repository -y ppa:vbernat/haproxy-{{haproxy_version}}

- name: Install haproxy {{haproxy_version}}
  apt: 
    name: haproxy={{haproxy_version}}.*
    update_cache: yes
    state: latest
