- include: "{{ansible_os_family}}.yml"

- name: Enable HAProxy Statistics Report
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      listen admin_stats 
          bind *:{{haproxy_stats_ports}} 
          mode http 
          maxconn 10 
          stats refresh 10s 
          stats uri /haproxy 
          stats realm Haproxy 
          stats auth {{haproxy_stats_username}}:{{haproxy_stats_password}}
          stats hide-version 
          stats admin if TRUE
          
- name: Start and enable haproxy service
  service:
    name: haproxy
    enabled: yes
    state: restarted

# set soft link, -b cover the exist links
- name: set soft link
  shell: |
    ln -sb /etc/haproxy  /data/wwwroot/haproxy
    ln -sb /etc/haproxy/haproxy.cfg  /data/config/haproxy.cfg
    
# Check version
- block:
  - name: Check HAProxy Version
    shell: echo `haproxy -v` >> /data/logs/install_version.txt

# check service state
- name: Check HAProxy Service
  shell: systemctl status haproxy |grep Active*
  register: check_haproxy_service
  notify: check_haproxy_service
