- include: "{{ansible_os_family}}.yml"

- name: Enable HAProxy Statistics Report
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      listen admin_stats 
          bind *:{{haproxy_stats_port}} 
          mode http 
          maxconn 10 
          stats refresh 10s 
          stats uri /haproxy 
          stats realm Haproxy 
          stats auth {{haproxy_stats_username}}:{{haproxy_stats_password}}
          stats hide-version 
          stats admin if TRUE

# configure log file. refer to: https://www.jianshu.com/p/baa296770bd5
- block:
  - name: Provides UDP syslog reception 01
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '#$ModLoad imudp'
      line: '$ModLoad imudp'
      backrefs: yes

  - name: Provides UDP syslog reception 02
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '#$UDPServerRun 514'
      line: '$UDPServerRun 514'
      backrefs: yes

  - name: Set save haproxy log
    blockinfile:
      path: /etc/rsyslog.conf
      block: |
        # Save haproxy log
        local2.*  /var/log/haproxy.log

  - name: Restart rsyslog
    shell: systemctl restart rsyslog

- name: Start and enable haproxy service
  service:
    name: haproxy
    enabled: yes
    state: restarted

# set soft link, -b cover the exist links
- name: set soft link
  shell: |
    ln -sb /etc/haproxy  /data/wwwroot/haproxy
    ln -sb /etc/haproxy/haproxy.cfg  /data/config/haproxy.cfg
    
# Check version
- block:
  - name: Check HAProxy Version
    shell: echo `haproxy -v` >> /data/logs/install_version.txt

# check service state
- name: Check HAProxy Service
  shell: systemctl status haproxy |grep Active*
  register: check_haproxy_service
  notify: check_haproxy_service
