- name: Download haproxy
  unarchive:
    src: "{{haproxy_meta[haproxy_version].latest_download_url}}"
    dest: /data/
    remote_src: yes

- name: Rename install package
  shell: mv haproxy-*  haproxy
  args:
    chdir: /data
 
 - name: Install required packages
   yum:
     name: [openssl,openssl-devel,systemd-devel.x86_64]
     
- name: Make install haproxy
  shell: make TARGET=linux-glibc  PREFIX=/etc/haproxy USE_OPENSSL=1 USE_SYSTEMD=1 USE_PCRE=1  USE_ZLIB=1  && make install
  args:
    chdir: /data/haproxy
    
- name: Copy service
  copy:
    src:  haproxy.service
    dest: /usr/lib/systemd/system/haproxy.service
