- name: Download haproxy
  unarchive:
    src: "{{haproxy_meta[haproxy_version].latest_download_url}}"
    dest: /data/
    remote_src: yes

- name: Rename install package
  shell: mv haproxy-*  haproxy
  args:
    chdir: /data
 
- name: Copy service
  copy:
    src:  haproxy.service
    dest: /usr/lib/systemd/system/haproxy.service
