- name: Download haproxy
  unarchive:
    src: "{{haproxy_meta[haproxy_version].latest_download_url}}"
    dest: /data/
    remote_src: yes

- name: Rename install package
  shell: mv haproxy-*  haproxy
  args:
    chdir: /data
    
- name: Install required packages
  yum:
    name: [gcc,gcc-c++,glibc,glibc-devel,pcre,pcre-devel,openssl,openssl-devel,systemd-devel,net-tools,vim,iotop,bc,zip,unzip,zlib-devel,lrzsz,tree,screen,lsof,tcpdump,wget,ntpdate]
    
- name: Make install haproxy
  shell: make TARGET=linux-glibc  PREFIX=/usr/local/sbin/haproxy USE_OPENSSL=1 USE_SYSTEMD=1 USE_PCRE=1  USE_ZLIB=1  && make install
  args:
    chdir: /data/haproxy

- name: Recursively change ownership of a directory
  file:
    path: /etc/haproxy
    state: directory
    recurse: yes
    
- name: Copy cfg
  template:
    src:  haproxy.cfg.jinja2
    dest: /etc/haproxy/haproxy.cfg
    
- name: Copy service
  template:
    src:  haproxy.service.jinja2
    dest: /usr/lib/systemd/system/haproxy.service
  when: haproxy_version != "1.7"

- name: Copy service
  shell: |
    cp /data/haproxy/examples/haproxy.init  /etc/init.d/haproxy
    chmod 755 /etc/init.d/haproxy
    systemctl daemon-reload
  when: haproxy_version == "1.7"

- name: Create haproxy symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /usr/local/sbin/haproxy,dest: /usr/sbin/haproxy}
